apiVersion: v1
kind: ConfigMap
metadata:
  name: additional-scrape-configs
  namespace: monitoring
data:
  additional-scrape-configs.yaml: |
    scrape_configs:
      - job_name: 'nginx'
        metrics_path: /metrics
        static_configs:
          - targets: ['nginx-prometheus-exporter.ingress-nginx.svc.cluster.local:9113']
