apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: additional-scrape-configs.yaml
  extraScrapeConfigs:
    - job_name: 'nginx-ingress'
      metrics_path: /metrics
      static_configs:
        - targets: ['nginx-ingress-controller.ingress-nginx.svc.cluster.local:10254']
    - job_name: 'wordpress'
      metrics_path: /metrics
      static_configs:
        - targets: ['wordpress.kuna-front.svc.cluster.local:80']
    - job_name: 'mysql'
      metrics_path: /metrics
      static_configs:
        - targets: ['mysql.kuna-back.svc.cluster.local:3306']
