apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts/
    chart: prometheus
    targetRevision: 19.7.2
    helm:
      values: |
        server:
          service:
            type: ClusterIP
        additionalScrapeConfigs:
          name: additional-scrape-configs
          key: additional-scrape-configs.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
